export { default as Hero } from "./Hero";
export { default as AboutMifa } from "./AboutMifa";
export { default as BestProjects } from "./BestProjects";
export { default as Blogs } from "./Blogs";
export { default as OurServices } from "./OurServices";
export { default as OurBeginning } from "./OurBeginning";
export { default as ContactUs } from "./ContactUs";
export { default as Footer } from "./Footer";
export { default as ScrollIndicator } from "./ScrollIndicator";
